"""init

Revision ID: 3812f6585c2c
Revises: 
Create Date: 2021-10-05 21:19:37.944916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3812f6585c2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalid_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('pwd', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index('IFK_AlbumArtistId', table_name='albums')
    op.drop_index('IFK_TrackAlbumId', table_name='tracks')
    op.drop_index('IFK_TrackGenreId', table_name='tracks')
    op.drop_index('IFK_TrackMediaTypeId', table_name='tracks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('IFK_TrackMediaTypeId', 'tracks', ['MediaTypeId'], unique=False)
    op.create_index('IFK_TrackGenreId', 'tracks', ['GenreId'], unique=False)
    op.create_index('IFK_TrackAlbumId', 'tracks', ['AlbumId'], unique=False)
    op.create_index('IFK_AlbumArtistId', 'albums', ['ArtistId'], unique=False)
    op.drop_table('users')
    op.drop_table('invalid_tokens')
    # ### end Alembic commands ###
